var map = {
  "id": "267",
  "pid": "97",
  "series_way_id": "267",
  "name_cn": "冠亚和",
  "name_en": "guanyahezhi",
  "price": "2",
  "bet_note": "从“大、小、单、双”中任何选择1个或1个以上项",
  "bonus_note": "冠军车号＋亚军车号＝冠亚和<br/><br/>冠亚和大小：“冠亚和”大于11时投注“大”的注单视为中奖，小于或等于11时投注“小”的注单视为中奖，其余视为不中奖。<br/><br/>冠亚和单双：“冠亚和”为单视为投注“单”的注单视为中奖，为双视为投注“双”的注单视为中奖。<br/>",
  "extra": {"0": 113960, "1": 91168, "2": 91168, "3": 113960},
  "extra_prize": {"0": "3.5100", "1": "4.3875", "2": "4.3875", "3": "3.5100"},
  "is_enable_extra": "1",
  "prize": "3.5100",
  "max_multiple": 113960,
  "bet_number": [{"冠亚和": ["大", "小", "单", "双"]}],
  "fullName_cn": "两面盘冠亚和",
  "fullName_en": "liangmianpan.zhixuan.guanyahezhi",
  "ok": true,
  "isdansuang": true,
  "isnotnumberSymble": false,
  "modesArray": [1, 0.1, 0.01],
  "mutipleAndModeObj": {"mode": 1, "times": 1},
  "bet_numberArrObj": [{"showgroup": false, "key": "冠亚和", "value": ["大", "小", "单", "双"]}],
  "selectarea": [{"key": "冠亚和", "value": [false, false, false, false]}],
  "selectareaPair": [{"showgroup": false, "key": "冠亚和", "value": ["大", "小", "单", "双"]}],
  "count": 0,
  "totals": 0
}
